---
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
        exclude: ^tests/classes/
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        exclude: ^tests/classes/
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.14.10'
    hooks:
      - id: ruff-check
        exclude: ^tests/classes/
      - id: ruff-format
        exclude: ^tests/classes/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: ["typer", "pytest"]
        exclude: ^tests/classes/
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/kieran-ryan/pyprojectsort
    rev: v0.4.0
    hooks:
      - id: pyprojectsort
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.36.0"
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-readthedocs
  - repo: https://github.com/regebro/pyroma
    rev: "5.0.1"
    hooks:
      - id: pyroma
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.13.13
    hooks:
      - id: typos
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.0.199
    hooks:
      - id: rumdl
  - repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v4.2.0  # Use the latest version
    hooks:
      - id: complexipy
        exclude: ^tests/classes/
...
